### ISSUE TITLE
How to use with combineReducers

### ISSUE THREAD

**Issue by tarim** [Storytel/react-redux-spinner#3]
Hi there,

I try to use your spinner on my application, and, I have more than ten reducers, and I used combineReducers. So, my question is, how we use it with multi reducers?

Thanks,

**Comment by noseglid** [comment]
The [usage example in the README](https://github.com/Storytel/react-redux-spinner#usage) is with `combineReducers`.

**Comment by tarim** [comment]
Hi @noseglid ,

I see that, but, it is not clear. ok, you added it to your reducer list, and use combineReducers to build your reducer. after how do you dispatch it? or how do you add it it your actions? 

Thanks,

for example I have a function for call api and get user details and dispatch them to redux store
export function getUser() {
	return function(dispatch){
		axios.get('/api/v1/Account/Get/User').then(response=>{
			dispatch(getUserSuccess(response));
		});
		
	}
}
