### ISSUE TITLE
Change UI of spinner

### ISSUE THREAD

**Issue by lalinda74** [Storytel/react-redux-spinner#34]
Is it possible to change the svg of spinner ?

**Comment by noseglid** [comment]
The spinner itself is delegate to [nprogress](https://github.com/rstacruz/nprogress). You can configure it by setting [its `template`](https://github.com/rstacruz/nprogress#template). This can be set through react-redux-spinner's `config` property.

Something like this
```
<Spinner config={{ template: '<div ...> ' }} />
```

**Comment by lalinda74** [comment]
I have used the config as below. 
`<Spinner config={{ template: '<div className="sp sp-wave"></div>' }}></Spinner>`

and I'm getting below error. 

> Uncaught TypeError: Cannot read property 'style' of null

**Comment by lalinda74** [comment]
> The spinner itself is delegate to [nprogress](https://github.com/rstacruz/nprogress). You can configure it by setting [its `template`](https://github.com/rstacruz/nprogress#template). This can be set through react-redux-spinner's `config` property.
> 
> Something like this
> 
> ```
> <Spinner config={{ template: '<div ...> ' }} />
> ```

@noseglid  I have used the config as below. 
`<Spinner config={{ template: '<div className="sp sp-wave"></div>' }}></Spinner>`

and I'm getting below error. 

> Uncaught TypeError: Cannot read property 'style' of null

**Comment by noseglid** [comment]
Do you have a stack trace? The `config` object [is passed verbatim](https://github.com/Storytel/react-redux-spinner/blob/master/src/spinner.js#L21-L22) to nprogress. I'm not seeing a `style` reference anywhere.
