### ISSUE TITLE
Does this work without using Webpack in your main application?

### ISSUE THREAD

**Issue by njj** [Storytel/react-redux-spinner#5]
I'm getting an error when the library is trying to load a css module:

`Browserify Error { [Error: Cannot find module '!!./../css-loader/index.js!./nprogress.css' from /node_modules/react-redux-spinner/dist']`

**Comment by noseglid** [comment]
No, you need webpack for now. I'll keep this issue open to possibly change that. Will require some changes in the build/publish process.
