### ISSUE TITLE
loading bar stays in view even after dispatching 'end'

### ISSUE THREAD

**Issue by bulkyracehorse512** [Storytel/react-redux-spinner#7]
even after dispatching `[ pendingTask ]: end` loader stays in view. loader only leaves view once the horizontal bar reaches the right side of the screen. doesn't seem to coordinate with actual dispatch of end action.

**Comment by noseglid** [comment]
Well, it attempts to do a smooth animation indicating that the progress quickly reached 100%. Is this what you're referring to? What would you rather want happen?

**Comment by avboltax** [comment]
that the animation is no longer visible once the success action fires. that the component updates it's state while the loader remains executing to completion is awkward.

**Comment by noseglid** [comment]
I don't understand. It will be visible for a second or so until it's spun up to "full screen width". Once there, it will fade away. This is how [nprogress works](http://ricostacruz.com/nprogress/) (which this spinner uses for animations.

Do you expect it to instantaneously disappear when end action is fired?
