### ISSUE TITLE
Build file to big

### ISSUE THREAD

**Issue by rakshans1** [Storytel/react-redux-spinner#8]
minify the build in webpack

![screenshot from 2016-08-15 19 39 48](https://cloud.githubusercontent.com/assets/12949352/17666900/1ea38d40-6320-11e6-857b-ee5e99a59432.png)

**Comment by noseglid** [comment]
👍
definitelyy want to do that

**Comment by rakshans1** [comment]
I tried to reduce the file size..
total size reducded from 688k to 4.6k
![screenshot from 2016-08-16 21 48 31](https://cloud.githubusercontent.com/assets/12949352/17706842/4cbbbe24-63fb-11e6-8f3b-a6b50431f909.png)

**Comment by noseglid** [comment]
I've added a comment on your PR, but otherwise looks good.

Mind telling me what you use to render those graphs?

**Comment by rakshans1** [comment]
Its webpack-visualizer-plugin
https://github.com/chrisbateman/webpack-visualizer

**Comment by noseglid** [comment]
Fixed with #9
